version: '2'
services:

  postgres:
    image: postgres:9.5
    env_file: .env
    volumes:
      - ./data-five-minutes/:/var/lib/postgresql/data/

  five_minutes:
    build: 
      context: ./five_minutes
      dockerfile: Dockerfile_local
    volumes:
      - ./five_minutes:/code
    links:
      - postgres:postgres
    depends_on:
      - postgres
    env_file: .env
    ports:
    - "8080:8080"
    command: ./run_local.sh

  redis:
    restart: always
    image: redis:4.0.6
