# Generated by Django 2.2.5 on 2019-09-17 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('0b9674ee-3469-4dd3-b48b-55ab6e76a5b6'), editable=False, primary_key=True, serialize=False)),
                ('already_used', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='events.Event')),
            ],
        ),
    ]
