# Generated by Django 2.2.5 on 2019-09-18 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('cd94a771-9b2d-45a8-932d-9ce52efbac04'), editable=False, primary_key=True, serialize=False),
        ),
    ]
