# Generated by Django 2.2.5 on 2019-09-23 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190917_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('949caf5a-ee35-4ea7-a723-67ad625ccd60'), editable=False, primary_key=True, serialize=False),
        ),
    ]
