# Generated by Django 2.2.5 on 2019-09-23 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190923_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_mark_used_ticket', 'Can mark as used a Ticket')]},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
