# Generated by Django 2.2.5 on 2019-09-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promoters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoter_events', to='promoters.Promoter')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_events', to='promoters.PromoterSpace')),
            ],
        ),
    ]
