# Generated by Django 2.2.5 on 2019-09-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_name', models.CharField(max_length=140)),
                ('contact_phone', models.CharField(max_length=32)),
                ('website', models.URLField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='PromoterSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='promoters.Promoter')),
            ],
        ),
    ]
